import { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "landing-page-clinica-de-estetica",
  title: "Landing Page para Clínica de Estética: Quando Usar e Quando Migrar para um Site Completo",
  excerpt: "Guia prático sobre landing page para clínica de estética: quando a página única converte bem, seus limites reais e o momento certo de evoluir para um site completo.",
  aiDescription: "Uma landing page converte bem para uma campanha paga ou um lançamento pontual, mas tem tetos claros: não aparece no Google organicamente, cobre um único serviço e vive apenas enquanto o anúncio roda. Este guia mostra quando ela basta, seus limites reais e o caminho para evoluir ao site completo.",
  date: "2026-07-29",
  lastModified: "2026-07-29",
  category: "Site Para Clinica De Estetica",
  image: "https://images.unsplash.com/photo-1592890288564-76628a30a657?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDA1ODQ2fDB8MXxzZWFyY2h8MXx8aGFuZCUyMHNjcm9sbGluZyUyMHNtYXJ0cGhvbmUlMjBvbiUyMGRlc2t8ZW58MXwwfHx8MTc4NTMwNTQyM3ww&ixlib=rb-4.1.0&q=80&w=1080",
  imageAlt: "Mão tocando a tela de um smartphone apoiado em uma mesa, preenchendo um formulário de contato online.",
  author: "Equipe Estetia",
  relatedSlugs: ["site-para-clinica-de-estetica-guia","quanto-custa-site-para-clinica-de-estetica","instagram-ou-site-clinica-de-estetica","erros-site-clinica-de-estetica","presenca-online-clinica-de-estetica"],
  faqs: [
    {
      "question": "Landing page substitui o site da clínica de estética?",
      "answer": "Não. A landing page cobre uma oferta e depende de tráfego pago contínuo; o site completo constrói alcance orgânico no Google, hospeda vários serviços e sustenta a presença da clínica no longo prazo."
    },
    {
      "question": "Preciso de uma landing page para rodar Google Ads?",
      "answer": "É recomendado: o Google avalia a experiência da página de destino na pontuação de qualidade do anúncio, e uma página lenta ou genérica encarece o clique."
    },
    {
      "question": "Posso usar fotos de antes e depois na landing page?",
      "answer": "Em anúncios pagos, não: a política de saúde do Google Ads proíbe imagens de antes e depois em procedimentos estéticos. No conteúdo orgânico da página, a Resolução CFM nº 2.336/2023 exige autorização da paciente e anonimato na imagem."
    },
    {
      "question": "Quanto tempo leva para colocar uma landing page no ar?",
      "answer": "Entre 3 e 7 dias úteis, contra semanas de um site completo, porque a estrutura é uma única página com um formulário — o gargalo costuma ser aprovar textos e fotos, não a construção técnica."
    },
    {
      "question": "Quando devo migrar da landing page para um site completo?",
      "answer": "Quando o custo por clique sobe porque a concorrência aumenta, quando a clínica já oferece mais de um procedimento relevante, ou quando você quer aparecer no Google sem depender de anúncio."
    }
  ],
  content: `
<p>Uma landing page converte bem para uma campanha paga ou um lançamento pontual, mas tem tetos claros: não aparece no Google organicamente, cobre um único serviço e vive apenas enquanto o anúncio roda. Este guia mostra quando ela basta, seus limites reais e o caminho para evoluir ao site completo.</p>
<section><h2>O Que É (e o Que Não É) uma Landing Page</h2><p>Uma <strong>landing page</strong> é uma página única, sem menu de navegação e sem links de saída, construída para uma única ação: fazer a visitante preencher um formulário ou clicar em um botão de WhatsApp. Ela nasce para receber tráfego pago ou o link da bio do Instagram — não para ser encontrada organicamente no Google.</p><h3>Landing page não é site pequeno</h3><p>O erro mais comum é tratar a landing page como uma versão enxuta do site institucional. Um <strong>site completo</strong> tem múltiplas páginas — serviços, sobre, contato, blog — que crescem e se indexam ao longo do tempo. A landing page tem uma página só, e essa página some do radar assim que a campanha para de rodar.</p><p>O relatório da Unbounce, que analisou 41 mil páginas e 464 milhões de visitas, encontrou uma <strong>taxa mediana de conversão</strong> de 6,6% entre todos os setores — um número que só faz sentido quando a página tem um objetivo único e claro, exatamente o papel de uma landing page.</p><p>Para clínicas de estética, isso funciona bem em cenários pontuais: uma promoção de Botox no mês da conscientização, o lançamento de um procedimento novo, ou a campanha de Dia das Mães com orçamento e prazo definidos.</p></section>
<section><h2>Quando a Landing Page Basta</h2><p>Se o objetivo é testar uma oferta antes de investir em um site completo, a landing page é a ferramenta certa: ela é rápida de publicar e barata de ajustar, então dá para medir a <strong>resposta real</strong> do público antes de comprometer orçamento maior.</p><p>Campanhas de curta duração são o caso de uso mais claro. Uma ação de Dia das Mães, uma condição especial de aniversário da clínica ou o lançamento de um equipamento novo têm início, meio e fim — a página existe só enquanto a campanha existe.</p><p>Quando o tráfego vem 100% de anúncios pagos (Google Ads ou Meta Ads) apontando para uma única oferta, a landing page concentra toda a atenção da visitante num só <strong>caminho de conversão</strong>, sem as distrações de um menu com dez opções.</p><p>Ela também resolve o problema do link na bio do Instagram: em vez de mandar a seguidora para um perfil genérico, a landing page entrega uma página com uma promessa clara e um formulário a um toque de distância.</p><p>Nesses cenários, o <strong>custo mais baixo</strong> e o prazo curto de entrega compensam a ausência de alcance orgânico — porque a clínica não está tentando ser encontrada no Google, está aproveitando um tráfego que já paga para chegar até ali.</p></section>
<section><h2>Quando Ela Limita: os Tetos da Página Única</h2><p>O primeiro teto é o <strong>SEO</strong>: uma landing page é uma URL só, e uma URL só não compete com um site que tem páginas dedicadas a cada procedimento, cada bairro e cada dúvida da paciente. Quem depende só da landing page fica invisível para quem pesquisa no Google sem ver anúncio.</p><h3>O teto do tráfego alugado</h3><p>Toda a conversão da landing page depende de <strong>tráfego pago contínuo</strong>. No dia em que o orçamento de anúncio acaba, a página para de receber visitas — diferente de um site que segue recebendo buscas orgânicas mesmo com a verba de mídia zerada.</p><p>A página única também trava a operação em uma <strong>oferta só</strong>: não há espaço para apresentar outros procedimentos, pacotes de manutenção ou conteúdo educativo que aqueça uma paciente que ainda não está pronta para agendar.</p><p>Existe ainda o teto regulatório: a Resolução CFM nº 2.336/2023 exige que o CRM e o RQE apareçam na página principal onde há publicidade médica, e a atualização de outubro de 2025 da política de saúde do Google Ads <strong>proíbe imagens de antes e depois</strong> em anúncios de procedimentos estéticos — uma landing page pensada só para converter, sem esses cuidados, corre risco de reprovação ou multa.</p><p>Por fim, como a maior parte do tráfego pago chega pelo celular, a página precisa cumprir os limiares de <strong>Core Web Vitals</strong> do Google — LCP abaixo de 2,5 segundos, por exemplo — porque cada 100 milissegundos extras de carregamento custam cerca de 1% de conversão perdida.</p></section>
<section><h2>Comparativo Direto: Landing Page vs. Site Completo</h2><p>Colocando lado a lado, fica claro que as duas ferramentas resolvem problemas diferentes — e a tabela abaixo resume onde cada uma <strong>vence</strong>.</p><table><thead><tr><th scope="col">Critério</th><th scope="col">Landing Page</th><th scope="col">Site Completo</th></tr></thead><tbody><tr><td>Objetivo</td><td>Uma oferta, uma ação</td><td>Múltiplos serviços e objetivos</td></tr><tr><td>Alcance no Google</td><td>Só via anúncio pago</td><td>Cresce organicamente com o tempo</td></tr><tr><td>Número de páginas</td><td>1</td><td>Vários (serviços, sobre, contato)</td></tr><tr><td>Prova social</td><td>Limitada ao espaço da página</td><td>Depoimentos, avaliações, portfólio completo</td></tr><tr><td>Custo inicial</td><td>Baixo</td><td>Médio a alto</td></tr><tr><td>Ciclo de vida</td><td>Curto, dura a campanha</td><td>Longo, ativo permanente da clínica</td></tr></tbody></table><p>Nenhuma das duas é superior em absoluto — a escolha depende do <strong>momento da clínica</strong>. Quem está testando uma oferta ou correndo uma campanha sazonal ganha com a landing page; quem quer ser encontrado no Google sem depender de anúncio precisa do site.</p><p>Um erro comum é escolher pelo preço mais baixo sem olhar o ciclo de vida: uma landing page barata que devia durar 30 dias, mas continua sendo o único ativo digital da clínica um ano depois, está custando <strong>oportunidade</strong>, não dinheiro.</p></section>
<section><h2>A Estrutura da Landing Page Que Converte</h2><p>A primeira dobra decide tudo: título com o <strong>benefício</strong> (não o nome técnico do procedimento), uma imagem real da clínica ou da equipe, e o botão de ação visível sem precisar rolar a tela.</p><p>Logo abaixo do título entra a prova social — uma avaliação do Google, um número de pacientes atendidas ou um selo de especialidade — porque a decisão de preencher o formulário acontece nos primeiros segundos, e a <strong>confiança</strong> vem antes do preço.</p><h3>O formulário é o único caminho de saída</h3><p>Sem menu, sem rodapé com links para redes sociais, sem nada que tire a visitante da página antes de ela converter. Os dados da Unbounce mostram por que isso importa: formulário de <strong>um campo</strong> converte a 13,4%, enquanto um formulário de nove campos cai para 3,6% — cada campo a mais é uma desistência a mais.</p><p>Como o tráfego pago chega majoritariamente pelo celular, o desenho precisa ser <strong>mobile-first</strong>: botão grande, texto curto, carregamento abaixo de 2,5 segundos de LCP. A conversão média em celular (2,8%) ainda fica atrás da de desktop (4,8%), e página lenta piora essa diferença.</p><p>E os cuidados regulatórios entram no design, não depois dele: CRM e RQE visíveis, linguagem sóbria e sem promessa de resultado, e nenhuma imagem de <strong>antes e depois</strong> se a página vai rodar como anúncio pago.</p></section>
<section><h2>O Caminho Racional: da Landing Page ao Site Completo</h2><p>O sinal mais claro para migrar é o <strong>custo por clique subindo</strong>: quando a concorrência no leilão de anúncios aumenta, depender só de mídia paga fica caro, e um site com alcance orgânico passa a ser mais barato no longo prazo do que continuar comprando cada visita.</p><p>Outro sinal é o <strong>catálogo de serviços crescendo</strong>. Quando a clínica passa de um procedimento de entrada para cinco ou seis, uma página única não tem espaço para apresentar todos com a profundidade que cada um merece.</p><p>Vale migrar também quando a clínica quer aparecer no <strong>Perfil da Empresa no Google</strong> com um site próprio linkado, ou quando começa a colher avaliações que merecem uma página de depoimentos maior do que um rodapé de landing page.</p><p>Na prática, a transição é mais simples do que parece: a landing page vencedora vira a primeira página de serviço dentro do site novo, preservando o texto e a estrutura que já provaram converter, em vez de recomeçar do zero.</p><p>Resumindo: a landing page é a ferramenta certa para testar uma oferta com prazo e orçamento definidos; o <strong>site completo</strong> é o ativo que sustenta a clínica no Google todos os dias do ano, com ou sem verba de anúncio.</p></section>
<section><h2>Fontes</h2><ul><li><a href="https://sistemas.cfm.org.br/normas/arquivos/resolucoes/BR/2023/2336_2023.pdf">Resolução CFM nº 2.336/2023</a> — Conselho Federal de Medicina (CFM), 2023-09-13</li><li><a href="https://support.google.com/adspolicy/answer/16551459?hl=pt">Atualização da Política de Cuidados de Saúde e Medicamentos (outubro de 2025)</a> — Google Ads Ajuda, 2025-10-01</li><li><a href="https://unbounce.com/average-conversion-rates-landing-pages/">What is the average landing page conversion rate? (Q4 2024 data)</a> — Unbounce, 2025-10-24</li><li><a href="https://developers.google.com/search/docs/appearance/core-web-vitals">Understanding Core Web Vitals and Google search results</a> — Google Search Central, 2025-12-10</li></ul></section>
`,
};
